#Extract LST values for random sample for each year
rm(list = ls())

setwd('E:/brazil_lst/code/daily_panel')

yrend <- c('03', '04', '05', '06', '07', '08', '09', '10', '11', '12')

for (yr in yrend) {
  
  print(yr)
  year_run <- paste('20',yr, sep='')
  
  filename <- file(paste('lst_dpanel_',yr,'_CL.R', sep=''), open='w')
  write('rm(list = ls())', filename)
  write('library(raster)', filename, append=TRUE)
  write('library(maptools)', filename, append=TRUE)
  write('library(reshape)', filename, append=TRUE)
  write('library(readstata13)', filename, append=TRUE)
  write('removeTmpFiles(h=1)', filename, append=TRUE)
  write('code_path <- "/cluster/shared/jangus01/brazil_lst/code_path"', filename, append=TRUE)
  write('data_path  <- "/cluster/tufts/bhattarai02/BrazilLST/LST_Aqua/"', filename, append=TRUE)
  write('out_path <- "/cluster/tufts/duncan/"', filename, append=TRUE)
  write('setwd(code_path)', filename, append=TRUE)
  write('#function that create year, month, doy, day, week_id, year panel', filename, append=TRUE)
  write('source("Get_ymdoys.R")', filename, append=TRUE)
  write('alldoys <- Get_ymdoys(2000,2014,gs_startMonth=1,gs_endMonth=12)', filename, append=TRUE)
  write('alldoys <- subset(alldoys, year >= 2003) #DOY for year', filename, append=TRUE)
  write('', filename, append=TRUE)
  write('# load sample data', filename, append=TRUE)
  write('ransample <- read.dta13(paste("mhv_4_nw_gfc.dta",sep=""))', filename, append=TRUE) 
  write('', filename, append=TRUE)
  write('# start Extracting LST values', filename, append=TRUE)
  write(paste('for (igsyear in ',year_run,') {', sep =''), filename, append=TRUE)
  write('setwd(data_path)', filename, append=TRUE)
  write('print(igsyear)', filename, append=TRUE)
  write('gs_id <- ransample[, c("x", "y", "u_id")]', filename, append=TRUE)
  write('gs_id_qc <- gs_id', filename, append=TRUE)
  write('# create spatial points data frame for LST extraction', filename, append=TRUE)
  write('ran_points <- gs_id', filename, append=TRUE)
  write('coordinates(ran_points)=~x+y', filename, append=TRUE)
  write('proj4string(ran_points)=CRS("+init=epsg:4326")', filename, append=TRUE)
  write('#subset year', filename, append=TRUE)
  write('ad <- subset(alldoys, year == igsyear)', filename, append=TRUE)
  write('yeardoy <- ad$yeardoy', filename, append=TRUE)
  write('for (i in yeardoy) {', filename, append=TRUE)
  write('print(i)', filename, append=TRUE)
  write('t <- Sys.time()', filename, append=TRUE)
  write('## MYD daytime LST and QC', filename, append=TRUE)
  write('lstDayfname <- paste(data_path,"/MYD11A1.A", i, ".LST_Day_1km.tif", sep="")', filename, append=TRUE)
  write('qcDayfname <- paste(data_path, "/MYD11A1.A", i, ".QC_Day.tif", sep="")', filename, append=TRUE)
  write('# check if the file exists in the folder or not', filename, append=TRUE)
  write('if (file.exists(lstDayfname)){', filename, append=TRUE)
  write('lst <- raster(lstDayfname) ', filename, append=TRUE)
  write('gs_id$newcol <- extract(lst, ran_points, method="simple", na.rm=FALSE)', filename, append=TRUE)
  write('gs_id$newcol <- gs_id$newcol* 0.02 - 273.15', filename, append=TRUE)
  write('names(gs_id)[names(gs_id) == "newcol"] <- paste(i)', filename, append=TRUE)
  write('}', filename, append=TRUE)
  write('if (file.exists(qcDayfname)){', filename, append=TRUE)
  write('qc <- raster(qcDayfname)', filename, append=TRUE)
  write('gs_id_qc$newcol <- extract(qc, ran_points, method="simple", na.rm=FALSE) ', filename, append=TRUE)
  write('names(gs_id_qc)[names(gs_id_qc) == "newcol"] <- paste(i)', filename, append=TRUE)
  write('removeTmpFiles(h=1) # clear memory', filename, append=TRUE)
  write('}', filename, append=TRUE)
  write('print(Sys.time()-t)', filename, append=TRUE)
  write('}', filename, append=TRUE)
  write('#reshape wide to long', filename, append=TRUE)
  write('gs_id <- melt(gs_id, id=c("u_id", "x", "y"))', filename, append=TRUE)
  write('names(gs_id)[names(gs_id) == "variable"] <- "yeardoy"', filename, append=TRUE)
  write('names(gs_id)[names(gs_id) == "value"] <- "lst"', filename, append=TRUE)
  write('#MODIS QC info', filename, append=TRUE)
  write('#reshape wide to long ', filename, append=TRUE)
  write('gs_id_qc <- melt(gs_id_qc, id=c("u_id"))', filename, append=TRUE)
  write('names(gs_id_qc)[names(gs_id_qc) == "variable"] <- "yeardoy"', filename, append=TRUE)
  write('names(gs_id_qc)[names(gs_id_qc) == "value"] <- "qc"', filename, append=TRUE)
  write('gs_id_qc$qcbin1 <- 0  # Highest Quality', filename, append=TRUE)
  write('gs_id_qc$qcbin1[gs_id_qc$qc == 0] <- 1', filename, append=TRUE)
  write('gs_id_qc$qcbin2 <- 0  # less than 1 K error', filename, append=TRUE)
  write('gs_id_qc[which(gs_id_qc$qc %in% c(1,5,17,21)), c("qcbin2")] <- 1', filename, append=TRUE)
  write('gs_id_qc$qcbin3 <- 0  #  1- 3 K error', filename, append=TRUE)
  write('gs_id_qc[which(gs_id_qc$qc %in% c(65,69,81,85,129,133,145,149)), c("qcbin3")] <- 1', filename, append=TRUE)
  write('#drop observations with > 3 K error', filename, append=TRUE)
  write('gs_id <- merge(gs_id, gs_id_qc, by=c("u_id", "yeardoy"))', filename, append=TRUE)
  write('#colnames(gs_id)', filename, append=TRUE)
  write('gs_id <- gs_id[, c("u_id","yeardoy","lst","qc","qcbin1", "qcbin2", "qcbin3")]', filename, append=TRUE)
  write('setwd(out_path)', filename, append=TRUE)
  write('save.dta13(gs_id, paste("lst_mhv_4_nw_",igsyear,".dta",sep=""))', filename, append=TRUE)
  write('}', filename, append=TRUE)
  close(filename) 
  
}
